### ISSUE TITLE
A suggestion to avoid CORS and different prod/dev

### ISSUE THREAD

**Issue by carsongee** [oleg-agapov/flask-vue-spa#2]
I really really enjoyed the writeup, but had a suggestion for avoiding the CORS setup and to make prod more similar to dev.  In my flask python I changed the catchall to:
```python
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def catch_all(path):
    # If we're in debug run it all to the javascript dev server
    if app.debug:
        return requests.get('http://localhost:8080/{}'.format(path)).text
    return render_template("index.html")
```
so that when the flask server is in debug it just proxies straight to the javascript server and you still have all the nice browsersync stuff going on

**Comment by oleg-agapov** [comment]
Indeed, it's a very elegant solution. Thanks @carsongee !
I'll try this and probably include to the article.
